### create user
POST http://localhost:3001/auth/signup
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "abcd1234",
  "firstName": "user",
  "lastName": "ABC",
  "phone": "0123334456"
}


### user signin
POST http://localhost:3001/auth/signin
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "abcd1234"
}


### find all user
GET http://localhost:3001/auth/

### find a user by id
GET http://localhost:3001/auth/1


### find all user by email
GET http://localhost:3001/auth?email=admin@example123.com


### delete user by id
DELETE http://localhost:3001/auth/3


### update user by id
PATCH http://localhost:3001/auth/3
Content-Type: application/json

{
  "email": "admin@test.com"
}


### sign out
POST http://localhost:3001/auth/signout